# config/routes.yaml

index:
    path: /
    controller: App\Controller\SorteoController::index

app_numero_sorteo:
    path: /sorteo/numero/{maximo}
    controller: App\Controller\SorteoController::numero
    defaults:
        maximo: 100

app_suma:
    path: /suma/{numero1}/{numero2}
    controller: App\Controller\SorteoController::suma
    defaults:
        numero1: 2
        numero2: 2

app_euromillones:
    path: /sorteo/euromillones
    controller: App\Controller\SorteoController::euromillones

app_nueva_apuesta:
    path: /sorteo/apuestas/nueva
    controller: App\Controller\SorteoController::nuevaApuesta

app_apuesta_creada:
    path: /apuesta/creada
    controller: App\Controller\SorteoController::apuestaCreada

app_apuesta_ver:
    path: /apuesta/ver/{id}
    controller: App\Controller\SorteoController::verApuesta

app_apuesta_lista:
    path: /apuesta/
    controller: App\Controller\SorteoController::listaApuestas

app_apuesta_editar:
    path: /apuesta/editar/{id}
    controller: App\Controller\SorteoController::editarApuesta